services:
  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    command: java -jar app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sample
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
